name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/maquinadeturing/maquinadeturing-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.READ_GITHUB_CONTAINER_REPOSITORY_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        bundle install --retry 3

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        external_repository: maquinadeturing/maquinadeturing.github.io
        publish_branch: main
        publish_dir: ./_site
        user_name: 'lamaquinadeturing'
        user_email: 'bot@lamaquinadeturing.su'
        full_commit_message: 'Deploy from GitHub Actions'